# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maurice Wipf – Developer
email: maurice.wipf@mauwi.me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mauwi.me" # the base hostname & protocol for your site
twitter_username: mauwi
github_username: mauricewipf
description: Find my latest projects.

# Build settings
markdown: kramdown
